import { dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { FlatCompat } from '@eslint/eslintrc';

const compat = new FlatCompat({ baseDirectory: dirname(fileURLToPath(import.meta.url)) });

const config = [
  ...compat.extends('next/core-web-vitals', 'next/typescript'),
  {
    ignores: [
      '.next/**', 'out/**', 'legacy/**', 'tools/**', 'public/**', 'e2e/**',
      'next-env.d.ts', // generated by Next; not ours to lint
    ],
  },
];

export default config;
